package com.tpi.pokemon.game.engine.effect;

public enum EffectTiming {
    ON_ABILITY_ACTIVATE,
    BEFORE_ATTACK,
    ON_ATTACK_DECLARE,
    ON_ATTACK_DECLARED,
    BEFORE_DAMAGE,
    AFTER_DAMAGE,
    AFTER_ATTACK,
    BEFORE_APPLY_CONDITION,
    BEFORE_RETREAT_COST_CALCULATION,
    ON_DAMAGE_RECEIVED,
    BETWEEN_TURNS,
    ON_PLAY_TRAINER,
    ON_TRAINER_PLAYED,
    ON_ATTACH_ENERGY,
    CONTINUOUS
}
