package com.tpi.pokemon.game.engine.effect;

public enum EffectType {
    DEAL_DAMAGE,
    HEAL_DAMAGE,
    APPLY_SPECIAL_CONDITION,
    DRAW_CARDS,
    DISCARD_ATTACHED_ENERGY,
    SEARCH_DECK,
    SHUFFLE_DECK,
    DISCARD_CARDS,
    ATTACH_ENERGY,
    MOVE_ENERGY,
    SWITCH_ACTIVE,
    PLACE_DAMAGE_COUNTERS,
    COIN_FLIP,
    COMPOSITE
}
