package com.tpi.pokemon.game.realtime;

public enum GameRealtimeEventType {
    GAME_CREATED,
    GAME_STARTED,
    PLAYER_JOINED,
    SETUP_UPDATED,
    VIEW_UPDATED,
    LOG_UPDATED,
    PLAYER_RECONNECTED,
    TURN_STARTED,
    ACTION_APPLIED,
    BASIC_PLAYED,
    ENERGY_ATTACHED,
    POKEMON_EVOLVED,
    RETREAT_PERFORMED,
    ATTACK_DECLARED,
    TURN_ENDED,
    ACTIVE_REPLACED,
    TRAINER_PLAYED,
    SELECTION_REQUIRED,
    SELECTION_RESOLVED,
    KNOCKOUT,
    PRIZE_TAKEN,
    SPECIAL_CONDITION,
    GAME_FINISHED
}
